const array = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/5npQuS3YbczUHz7NONIpfulA1PT.jpg',
      id: 288235,
      name: 'Cat Run Collection',
      original_language: 'en',
      original_name: 'Cat Run Collection',
      overview:
        'Cat Run is a 2011 American comedy action film directed by John Stockwell. Paz Vega stars as Catalina "Cat" Rona, a sexy, high-end escort holding the key evidence to a scandalous government cover-up. Two bumbling young detectives then become her unlikely protectors from a ruthless assassin hired to silence her. This was followed by the 2014 sequel Cat Run 2, with Scott Mechlowicz and Alphonso McAuley reprising their roles as Anthony and Julian.',
      poster_path: '/60qNeMnm1WhKYxGOr5VP3mVTnDC.jpg',
    },
    {
      adult: false,
      backdrop_path: '/mMN1S9UkPntpgD5NkzUqzPDCyMn.jpg',
      id: 272673,
      name: 'Cat People Collection',
      original_language: 'en',
      original_name: 'Cat People Collection',
      overview: 'Cat People Collection',
      poster_path: '/faeXfLsDaqG2gOCF4GlzXPTum9E.jpg',
    },
    {
      adult: false,
      backdrop_path: null,
      id: 595366,
      name: 'Samurai Cat Collection',
      original_language: 'en',
      original_name: 'Samurai Cat Collection',
      overview:
        'In the Edo era, there was a legendary samurai named Kyutaro Madarame who was feared as "Madara the Devil". He was somehow hired to kill a cat named Tamanojo. Just before Kyutaro slashed down upon Tamanojo, he saw that Tamanojo was looking into his eyes and saying "meow". But why?',
      poster_path: null,
    },
    {
      adult: false,
      backdrop_path: '/h524bp78CYxG2TTEiwCLzQVyBiS.jpg',
      id: 476056,
      name: 'Fritz the Cat Collection',
      original_language: 'en',
      original_name: 'Fritz the Cat Collection',
      overview:
        "A hypocritical swinging college student cat raises hell in a satiric vision of various elements on the 1960's.",
      poster_path: '/73NUFzgLhJrnJBpWN8zU3QtHD9u.jpg',
    },
    {
      adult: false,
      backdrop_path: '/6IAQmAfTF6Xtb78s5BBLVPtTiQl.jpg',
      id: 119234,
      name: 'Stray Cat Rock Collection',
      original_language: 'en',
      original_name: 'Stray Cat Rock Collection',
      overview: 'Stray Cat Rock pinky violence films.',
      poster_path: '/lTX22cP5IrdzTF0n0giYbjPi45s.jpg',
    },
    {
      adult: false,
      backdrop_path: '/xwWv4bPe5tFi7elJESfQz2NMkKw.jpg',
      id: 706894,
      name: 'Cat Girls Gamblers Collection',
      original_language: 'ja',
      original_name: 'TOBA NO MESU NAKO Collection',
      overview: 'Cat Girls Gamblers Collection',
      poster_path: '/ag0ZQYa8PvWgyz4LfNyeftUlqfB.jpg',
    },
    {
      adult: false,
      backdrop_path: '/jMM7RKpiXNKHfKB2pr5tvUfjiG6.jpg',
      id: 77300,
      name: 'Leopold the Cat Adventures',
      original_language: 'ru',
      original_name: 'Приключения кота Леопольда (Коллекция)',
      overview:
        'Throughout the series, a kind and intelligent Leopold the Cat has to deal with two mischievous mice, Grey and White.',
      poster_path: '/ot0KIARP1ODD4xu7KMlw7GMD13r.jpg',
    },
    {
      adult: false,
      backdrop_path: '/bpxsiSYttnlsPdwx6wEfzWaRKIz.jpg',
      id: 349336,
      name: 'Macskafogó gyűjtemény',
      original_language: 'hu',
      original_name: 'Macskafogó gyűjtemény',
      overview: '',
      poster_path: '/rWwH4KxPZV1MfpyzPscGAJQKlL.jpg',
    },
    {
      adult: false,
      backdrop_path: '/wwTxNzXfZSvqi2cLOAaEEXJDozW.jpg',
      id: 266731,
      name: 'Jango Collection',
      original_language: 'de',
      original_name: 'Jango Collection',
      overview:
        'The first spaghetti westerns as a trilogy with Terence Hill and Bud Spencer as Jango as Dan in the lead roles. It begins with "God Forgives ... I Do not!" Merges seamlessly into the nights movie "Ace High" over and ends with "Boot Hill". Unlike the later films with the two series is made very seriously and accordingly adapted bloody, even if some ridiculous elements can already be seen here that distinguish the duo later.',
      poster_path: '/dRsu5FI3ZTVSiBVDYYIeQ0wzEPs.jpg',
    },
    {
      adult: false,
      backdrop_path: '/gzgxqe7C90l8wG9v7lHVYUK71QI.jpg',
      id: 645991,
      name: 'Cattle Hill',
      original_language: 'en',
      original_name: 'KuToppen Collection',
      overview:
        'Klara is a little cow, who lives in the city with her mum and dreams of becoming a music star.',
      poster_path: '/18JorCxQO121RsHoVSAAFCyuqQo.jpg',
    },
    {
      adult: false,
      backdrop_path: null,
      id: 697304,
      name: 'Cats & Dogs',
      original_language: 'cs',
      original_name: 'Cats & Dogs',
      overview: '',
      poster_path: '/sNNxLRtwl7ofzcrFFROPSlYPKxM.jpg',
    },
    {
      adult: false,
      backdrop_path: '/bYM1XFABSpy0QtAEzr7dks8QRWY.jpg',
      id: 87014,
      name: 'Cats & Dogs Collection',
      original_language: 'en',
      original_name: 'Cats & Dogs Collection',
      overview:
        'Cats and Dogs\r Witness this epic "tail" of what happens when an eccentric professor makes a discovery that could tip the age-old balance of pet power. Now, an inexperienced young beagle pup named Lou is about to begin the ultimate mission im-paws-ible: to save humanity from a total cat-tastrophe!  Cats and Dogs 2 - Revenge of the Kitty Galore\r The epic struggle between cats and dogs for control of planet Earth continues in this sequel to the 2001 smash hit that had pet owners all across the world looking at their house pets in a whole new light. The ongoing war between the canine and feline species is put on hold when they join forces to thwart a rogue cat spy with her own sinister plans for conquest.',
      poster_path: '/3mb7yUgq4BPdqhPpBKAX4QLetby.jpg',
    },
    {
      adult: false,
      backdrop_path: null,
      id: 587607,
      name: 'Frog Dog Log Catalog',
      original_language: 'en',
      original_name: 'Frog Dog Log Catalog',
      overview:
        'Films from the Bog, starring Frog, Dog, Log, Hog, and/or Fog. Created by Jared D. Weiss.',
      poster_path: null,
    },
    {
      adult: false,
      backdrop_path: '/f43OAmK1jZYiLw5PCJTrym7X36S.jpg',
      id: 708213,
      name: 'The Crazy Cats Collection',
      original_language: 'en',
      original_name: 'The Crazy Cats Collection',
      overview:
        'A series of films staring the popular Crazy Cats musical comedy group.',
      poster_path: null,
    },
    {
      adult: false,
      backdrop_path: '/c4V0yBF2djwnfAKPDO7ocIswa40.jpg',
      id: 109292,
      name: 'Die Wanderhure Filmreihe',
      original_language: 'de',
      original_name: 'Die Wanderhure Filmreihe',
      overview: '',
      poster_path: '/uNB7TmFg1mHZctOXY74b48cD4bj.jpg',
    },
    {
      adult: false,
      backdrop_path: '/x5S20jb15ruRQd0gY1ZST9dJP7b.jpg',
      id: 400700,
      name: 'Neighbors Collection',
      original_language: 'en',
      original_name: 'Neighbors Collection',
      overview:
        'A comedy film series that follows a couple, Mac & Kelly Radner, who come into conflict with a fraternity, led by Teddy Sanders that has recently moved in next door. They later come into conflict with a new sorority, led by Shelby that rents next door.',
      poster_path: '/sQshvy7vnEBafeWmO6fQTNIvV2C.jpg',
    },
    {
      adult: false,
      backdrop_path: '/37xamYKRUGCRux532lKcZdVGYuR.jpg',
      id: 86066,
      name: 'Despicable Me Collection',
      original_language: 'en',
      original_name: 'Despicable Me Collection',
      overview:
        'The Despicable Me franchise centers on Gru, a super-villain (who later becomes a dad and superhero); his yellow-coloured Minions; and his three orphan girls, Margo, Edith and Agnes.',
      poster_path: '/95prV91f4DxkBnLU43YjLbU1m3q.jpg',
    },
    {
      adult: false,
      backdrop_path: '/7TIT28YbhAOeQGD2q2hJ9j83jI1.jpg',
      id: 93220,
      name: 'Miss Congeniality Collection',
      original_language: 'en',
      original_name: 'Miss Congeniality Collection',
      overview: 'An undercover agent',
      poster_path: '/wgQWsSsvB1iu1Pwc4nUP9E5bRzs.jpg',
    },
  ],
  total_pages: 1,
  total_results: 18,
};
